# Generated by Django 5.2.1 on 2026-05-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
